/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author isaac
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hboLogo = new javax.swing.JLabel();
        RMLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fightPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        uiQueueTlou1 = new ui.UiQueue("Prioridad 1");
        uiQueueRm1 = new ui.UiQueue("Prioridad 1");
        uiQueueRm2 = new ui.UiQueue("Prioridad 2");
        uiQueueRm3 = new ui.UiQueue("Prioridad 3");
        uiQueueRmBooster = new ui.UiQueue("Cola de refuerzo");
        uiQueueTlou2 = new ui.UiQueue("Prioridad 2");
        uiQueueTlou3 = new ui.UiQueue("Prioridad 3");
        uiQueueTlouBooster = new ui.UiQueue("Cola de refuerzo");
        tlouBackground = new javax.swing.JLabel();
        rmBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hboLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hboLogo.png"))); // NOI18N
        jPanel1.add(hboLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 80));

        RMLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/RMLogo.png"))); // NOI18N
        jPanel1.add(RMLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TLOULogo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        fightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/vs.png"))); // NOI18N
        fightPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        jPanel1.add(fightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 430, 340));
        jPanel1.add(uiQueueTlou1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, -1, -1));
        jPanel1.add(uiQueueRm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        jPanel1.add(uiQueueRm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel1.add(uiQueueRm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel1.add(uiQueueRmBooster, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));
        jPanel1.add(uiQueueTlou2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 200, -1, -1));
        jPanel1.add(uiQueueTlou3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 300, -1, -1));
        jPanel1.add(uiQueueTlouBooster, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 400, -1, -1));

        tlouBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/TLOUWallpaper.png"))); // NOI18N
        jPanel1.add(tlouBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, -1, -1));

        rmBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/rmWallpaper.png"))); // NOI18N
        jPanel1.add(rmBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(-540, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RMLogo;
    private javax.swing.JPanel fightPanel;
    private javax.swing.JLabel hboLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel rmBackground;
    private javax.swing.JLabel tlouBackground;
    private ui.UiQueue uiQueueRm1;
    private ui.UiQueue uiQueueRm2;
    private ui.UiQueue uiQueueRm3;
    private ui.UiQueue uiQueueRmBooster;
    private ui.UiQueue uiQueueTlou1;
    private ui.UiQueue uiQueueTlou2;
    private ui.UiQueue uiQueueTlou3;
    private ui.UiQueue uiQueueTlouBooster;
    // End of variables declaration//GEN-END:variables

    public UiQueue getUiQueueRm1() {
        return uiQueueRm1;
    }

    public UiQueue getUiQueueTlou1() {
        return uiQueueTlou1;
    }

    public UiQueue getUiQueueRm2() {
        return uiQueueRm2;
    }

    public UiQueue getUiQueueRm3() {
        return uiQueueRm3;
    }

    public UiQueue getUiQueueRmBooster() {
        return uiQueueRmBooster;
    }

    public UiQueue getUiQueueTlou2() {
        return uiQueueTlou2;
    }

    public UiQueue getUiQueueTlou3() {
        return uiQueueTlou3;
    }

    public UiQueue getUiQueueTlouBooster() {
        return uiQueueTlouBooster;
    }
    
    

    
}
