/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import classes.dataStructures.Queue;
import javax.swing.JPanel;

/**
 *
 * @author isaac
 */
public class UiQueue extends javax.swing.JPanel {

    /**
     * Creates new form UiQueue
     */
    public UiQueue() {
        initComponents();
        this.mainPane.setOpaque(false);
        this.setOpaque(false);
    }
    
    public UiQueue(String title) {
        initComponents();
        this.mainPane.setOpaque(false);
        this.setOpaque(false);
        this.titleLabel.setText(title);
    }
    
    public void updateUiQueue(Queue chaptersQueue){
        this.queueLabel.setText(chaptersQueue.buildStringForUiQueue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPane = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        queueLabel = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPane.setBackground(new java.awt.Color(102, 0, 102));
        mainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("Cola de Prioridad");
        mainPane.add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, 40));

        jScrollPane1.setViewportView(queueLabel);

        mainPane.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 290, 60));

        titleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel1.setText("Final");
        mainPane.add(titleLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 40));

        titleLabel2.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel2.setText("Inicio");
        mainPane.add(titleLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 100));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPane;
    private javax.swing.JLabel queueLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    // End of variables declaration//GEN-END:variables

}
