/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import classes.Chapter;
import javax.swing.ImageIcon;

/**
 *
 * @author isaac
 */
public class UiRing extends javax.swing.JPanel {

    /** Creates new form UiRing */
    public UiRing() {
        initComponents();
        this.setOpaque(false);
        this.mainPane.setOpaque(false);
        this.crownLabel.setDisabledIcon(new ImageIcon("src\\assets\\boxing.png"));
        this.crownLabel.setEnabled(false);
    }
    

    
    public void updateRing(Chapter chapter) {
        this.crownLabel.setEnabled(false);
        this.idTitle.setText(chapter.getPcb().getCompleteId());
        this.nameTitle.setText(chapter.getChapterName());
       
    }
    
    public void setWinner(){
        this.crownLabel.setEnabled(true);
    }
    
    public void setCharactericon(int index) {
        String aux = String.valueOf(index);
        String power = String.valueOf(100-(index*10));
        this.iconLabel.setIcon(new ImageIcon("src\\assets\\"+aux+".png"));
        this.powerLabel.setText(power);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mainPane = new javax.swing.JPanel();
        idTitle = new javax.swing.JLabel();
        nameTitle = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        crownLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        powerLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPane.setBackground(new java.awt.Color(51, 51, 51));
        mainPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idTitle.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        idTitle.setText("Id");
        mainPane.add(idTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 25));

        nameTitle.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nameTitle.setText("Nombre del cap");
        mainPane.add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 25));

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/1.png"))); // NOI18N
        mainPane.add(iconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, -1, -1));

        crownLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/crown.png"))); // NOI18N
        mainPane.add(crownLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel1.setText("Poder:");
        mainPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        powerLabel.setText("nro Poder");
        mainPane.add(powerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        add(mainPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 350));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel crownLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel idTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPane;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JLabel powerLabel;
    // End of variables declaration//GEN-END:variables

}
